# -*- coding: utf-8 -*-
"""pythonbasic_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18i1BV5agp67_qtetS3v2qzwn2M83WtlQ
"""

from functools import reduce
#importing the reduce from the functools

#for the uppercase

fruits=["Apple", "Banana", "Pear", "Apricot", "Orange" ]

uppercase_fruits=list(map(str.upper, fruits))

print(uppercase_fruits)




#for the filtering with A
fruits=["Apple", "Banana", "Pear", "Apricot", "Orange" ]

filter_fruits= list(filter(lambda x: x.startswith('A'), fruits))

print(filter_fruits)

#for reduce in py
fruits=["Apple", "Banana", "Pear", "Apricot", "Orange" ]

concat=reduce(lambda x,y:x + " " + y, fruits)

print(concat);



#for with comprehension
number = int(input("Enter a number: "))
multiples = (number * i for i in range(1, 11))

for multiple in multiples:
    print(multiple)




#for the multiplication without comprehension

def generate_multiples(number):
  for i in range (1,11):
    yield number*i;

numbers=generate_multiples(5);

for multiple in  numbers:
  print(multiple);




# for using zip

food=["pizza","momo","kimbap"]
amount=[500, 200, 250]

zipped=zip(food,amount)
list_zip=list(zipped)
print(list_zip);




#creating a dictionary for combining two lists

list_one = ['a', 'b', 'c', 'd', 'e']
list_two = [1, 2, 3, 4, 5]

combined={key: value for key, value in zip(list_one, list_two)}
print(combined)



#dictionary max aand min value
diction = {'a': 10, 'b': 20, 'c': 5, 'd': 30, 'e': 15}
diction_1={'Theodore': 19, 'Roxanne': 22, 'Mathew': 21, 'Betty': 20}

max_key = max(diction, key=diction.get)
max_key2=max( diction_1, key=diction_1.get)
min_key = min(diction,  key=diction.get)
min_key2 = min(diction_1,  key=diction_1.get)


print("Key of maximum value:", max_key)
print("Key of minimum value:", min_key)

print("Key of maximum value:", max_key2)
print("Key of minimum value:", min_key2)



#for excluding the number from the list 
exclude_numbers=[ 5, 6, 12, 15]
numbers= list(range(21)) # to include from 0 to 20

for num in exclude_numbers:
  if num in numbers:
    numbers.remove(num)

print(numbers);


#for removing duplicates 
given_list=[0, 0, 1, 2, 3, 4, 4, 5, 6, 6, 6, 7, 8, 9,
4, 4]
print("original list", given_list)
removed_duplicates=[*set(given_list)];
print("removed duplicates list: ", removed_duplicates);


#for finding the value 
list= ['apple', 'banana', 'pear', 'orange']
list_value={word: len(word) for word in list}
print(list_value);